spring.application.name=aplikasi-cetak-stiker

# ==============================
# Database SQLite
# ==============================
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:./data/cetak-stiker.db
spring.datasource.username=
spring.datasource.password=

# ==============================
# JPA & Hibernate
# ==============================
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.security.user.name=admin
spring.security.user.password=admin123

# ==============================
# JPA & Hibernate
# ==============================
app.upload.dir=./uploads/images