package com.girsang.stiker.model.dto.response

data class DataStikerResponse(
    val id: String = "",
    var umkmId: String,
    var namaUsaha: String,
    var namaPemilik: String,
    var noTelpon: String,
    var whatsapp: String,
    var facebook: String,
    var instagram: String,
    var alamat: String,
    var barangId: String,
    var namaBarang: String,
    var stokBarang: Long,
    var kodeStiker: String = "",
    var namaStiker: String = "",
    var panjang: Double = 0.0,
    var lebar: Double = 0.0,
    var ukuran: String = "",
    var catatan: String? = "",
    var status: Boolean = true,
    var pathGambar1: String = "",
    var pathGambar2: String = "",
    var pathTIF: String = "",
    var lebarKertas: Double = 0.0,
    var tinggiKertas: Double = 0.0,
    var offsetX: Double = 0.0,
    var offsetY: Double = 0.0,
    var width: Double = 0.0,
    var height: Double = 0.0,
    var dpiX: Double = 0.0,
    var dpiY: Double = 0.0,
    var imageWidthMM: Double = 0.0,
    var imageHeightMM: Double = 0.0,
    var dibuatPada: Long,
    var diubahPada: Long
)